>```https://www.BMOFinancialGroup.com/Autotools
> new: 'document',
>    name: 'Chief Executive Account',
>      holder-name: 'Chais Thomas Fitzwater',
> /.outline
> 	style: '.JS',
> font: 'times new roman',
>     color: 'black',
> key: `[
'(# "Symbolizes a text which is bold in nature".), (* "Symbolizes importance in the text".), (! "Symbolizes an action event which is either pre, post, present in nature".), (^ "Symbolizes a fix or edit in the text for typogrophy errors or updates".),(@ "Symbolizes a person or something being located 'at' another location".), ("$ Symbolized an edit to to command line or $$ Symbolizes a link".),
]`
		button: 'create.new.button'
			button: 'opens document outline',
			[https://github.com/ETEnterprises1/Master/new/dev.azure.com/-ETEnterprises1/BMO%20Financial%20Inc](https://www.etenterprises1.com/master/chiefexecutiveaccount/outline)
  ```
