# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: https://github.com/Federal-Reserve-Bitcoin-Banking-Inc/Master.git,
  push: 'main branch'
    branches: [ "Master" ]
  pull_request: -a
    branches: [ "Master" ]

jobs: Run|
  build: '.javascript'

    runs-on: ubuntu-latest

    strategy: 'default'
      matrix: 'Node.js latest'`
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: write, edit, check, run, deploy
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with: jobs
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
